---
- name: Configure IPv6 in docker
  ansible.builtin.template:
    src:  "docker-daemon.json.j2"
    dest: /etc/docker/daemon.json
  become: true
  notify: docker_restart

- name: Configure Linux kernel to allow IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.forwarding
    value: "{{ docker_ipv6_enabled | ternary('1', '0') }}"
    sysctl_set: true
    state: present
    reload: true
  become: true
  changed_when: false

- name: Configure Linux kernel to allow IP forwarding at startup
  ansible.builtin.template:
    src: sysctl-ipv6-forwarding.sh.j2
    dest: /etc/network/if-pre-up.d/sysctl-ipv6-forwarding
    mode: 0755
  become: true
